INFO:torchtune.utils._logging:Logging /tmp/Llama-3.2-3B/torchtune_config.yaml to W&B under Files
Traceback (most recent call last):
  File "/home/sahanp/.conda/envs/parity-bench/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/_cli/run.py", line 196, in _run_cmd
    self._run_single_device(args, is_builtin=is_builtin)
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/_cli/run.py", line 102, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 669, in <module>
    sys.exit(recipe_main())
             ^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/config/_parse.py", line 99, in wrapper
    sys.exit(recipe_main(conf))
             ^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 663, in recipe_main
    recipe.setup(cfg=cfg)
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 206, in setup
    ckpt_dict = self.load_checkpoint(cfg.checkpointer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/recipes/full_finetune_single_device.py", line 146, in load_checkpoint
    self._checkpointer = config.instantiate(
                         ^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/config/_instantiate.py", line 112, in instantiate
    return _instantiate_node(OmegaConf.to_object(config), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/config/_instantiate.py", line 33, in _instantiate_node
    return _create_component(_component_, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/config/_instantiate.py", line 22, in _create_component
    return _component_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/training/checkpointing/_checkpointer.py", line 355, in __init__
    self._checkpoint_paths = self._validate_hf_checkpoint_files(checkpoint_files)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/training/checkpointing/_checkpointer.py", line 395, in _validate_hf_checkpoint_files
    checkpoint_path = get_path(self._checkpoint_dir, f)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahanp/.conda/envs/parity-bench/lib/python3.11/site-packages/torchtune/training/checkpointing/_utils.py", line 165, in get_path
    raise ValueError(f"No file with name: {filename} found in {input_dir}.")
ValueError: No file with name: model-00001-of-00002.safetensors found in /tmp/Llama-3.2-3B.
